site_name: American Beauty Institute

repo_url: https://github.com/AmericanBeautyInstitute/data-platform
repo_name: data-platform

theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/favicon.png
  features:
    - search.highlight
    - search.suggest
  palette:
    primary: indigo

nav:
  - Home: index.md
  - About: about.md
