storage:
  sqlite:
    base_dir: /var/dagster/home

code_server:
  grpc:
    host: 127.0.0.1
    port: 4266

concurrency:
  pools:
    default_limit: 1

run_monitoring:
  enabled: true
  free_slots_after_run_end_seconds: 60

telemetry:
  enabled: false

