storage:
  sqlite:
    base_dir: /var/dagster/home

run_launcher:
  module: dagster.core.launcher
  class: DefaultRunLauncher

executor:
  module: dagster.core.executor.multiprocess
  class: MultiprocessExecutor
  config:
    max_concurrent: 1

telemetry:
  enabled: false
