gateways:
  bigquery:
    connection:
      type: bigquery
      method: service-account
      project: american-beauty-institute
      keyfile: ${GOOGLE_APPLICATION_CREDENTIALS}
      location: US

default_gateway: bigquery

model_defaults:
  dialect: bigquery
  start: '2024-01-01'
  cron: '@daily'

linter:
  enabled: true
  rules:
    - ambiguousorinvalidcolumn
    - invalidselectstarexpansion
    - noambiguousprojections
